name: Validate Turtle Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Raptor2 for Turtle validation
        run: |
          sudo apt-get update
          sudo apt-get install -y raptor2-utils

      - name: Find and validate Turtle files
        run: |
          find . -name "*.ttl" -exec rapper -i turtle -c {} \;
